# Generated by Django 3.2 on 2021-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210203_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=50, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='majority',
            field=models.CharField(default='', max_length=50, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=50, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(default='', max_length=50, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='wx_num',
            field=models.CharField(default='', max_length=50, verbose_name='微信号码'),
        ),
    ]
